title: Yves De Jesus
logo: https://i.imgur.com/y07a9xI.jpg
email: yvesmango@gmail.com
description: <p>Network Analysis.</br>Machine Learning.</br>Data Visualization.</p>
favicon: true
color-scheme: light

url: https://yvesmango.github.io/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: <a href="https://github.com/yvesmango" target="_blank"><i class="fa-brands fa-github fa-lg"></i> GitHub</a>
    icon: 
    link:
  - name: <a href="https://twitter.com/yvesmango_" target="_blank"><i class="fa-brands fa-twitter fa-lg"></i> Twitter</a>
    icon:
    link:

navigation:
  - name: home
    link: ./
  - name: projects
    link: ./projects
  - name: about
    link: ./aboutme
  - name: sample
    link: ./sample.html
    sublist:
      - name: Image
        link: ./sample.html#small-image
