title: Yves De Jesus
logo: https://i.imgur.com/fPr5Qb4.png
email: yvesmango[at]gmail.com
description: data analyst specializing in spatial analysis (GIS)
favicon: true
color-scheme: light

url: https://yvesmango.github.io/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: <a href="https://github.com/yvesmango" target="_blank"><i class="fa-brands fa-github fa-lg"></i> GitHub</a>
    icon: 
    link:
  - name: <a href="https://mastodon.social/@yvesmango" target="_blank"><i class="fa-brands fa-mastodon fa-lg"></i> Mastodon</a>
    icon:
    link:
  - name: <a href="https://maps.app.goo.gl/JUh1S2CpjMbCttwv8" target="_blank"><i class="fa-solid fa-map-pin"></i> Boston, MA</a>
    icon: 
    link:

navigation:
  - name: home
    link: ./
  - name: projects
    link: ./projects
  - name: about
    link: ./aboutme
